name: Build CI container

on:
  push:
    branches: [main]
    paths:
      - ".github/tauri-ci.Dockerfile"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and push CI image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .github
          file: .github/tauri-ci.Dockerfile
          push: true
          tags: |
            ghcr.io/streamndad/tauri-ci:22.04
            ghcr.io/streamndad/tauri-ci:latest
